version: "3.9"
services:

  database:
    image: mysql:8.0.29
    container_name: crm-database
    restart: always
    command: [ "mysqld", "--default-authentication-plugin=mysql_native_password" ]
    environment:
      - MYSQL_DATABASE=crm
      - MYSQL_USER=crm
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql

  webserver:
    build: docker/nginx
    container_name: crm-webserver
    working_dir: /var/www/application
    volumes:
      - .:/var/www/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - php-fpm

  php-fpm:
    build: docker/php-fpm
    container_name: crm-php
    working_dir: /var/www/application
    volumes:
      - .:/var/www/application
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf

  nodejs:
    build: docker/node
    container_name: crm-node
    working_dir: /var/www/application
    volumes:
      - .:/var/www/application
    expose:
      - 8080
    ports:
      - "8080:8080"
    tty: true
    environment:
      NODE_ENV: development

volumes:
  db:
    driver: local
